name: Publish npm dynamark package

on:
  push:
    tags:
      - '*'

jobs:

  publish:
    name: Run publish workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install, build and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Install dependencies
          npm i

          # Gather data
          npm run build

          # Publish new version to npm registry
          npm publish
